<a href="https://colab.research.google.com/github/suhithreddyc/PESU_io_Assignments/blob/main/IO_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/PESUIODATABASE.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [4]:
y

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[ 4.18306047e-01,  1.60053039e+00],
       [-7.33900332e-01, -6.32442668e-01],
       [-1.05108261e+00,  1.02504808e+00],
       [-1.99063184e-02, -5.37429299e-01],
       [ 1.28387980e+00, -8.32002520e-01],
       [-7.66954064e-01, -8.17702849e-01],
       [-1.10667298e+00,  1.23922537e+00],
       [-6.25724479e-01, -7.65906263e-01],
       [ 7.77524372e-02, -5.33933824e-01],
       [ 6.28647982e-01, -5.56177756e-01],
       [-6.75472016e-01,  5.90973622e-01],
       [ 2.00451899e-01,  6.10039850e-01],
       [ 1.75798385e+00,  2.01108983e+00],
       [-3.04368745e-01,  1.22619678e+00],
       [ 7.76388150e-01, -8.26600422e-01],
       [-1.05993033e+00, -7.30951512e-01],
       [-1.03138393e+00, -6.67079649e-01],
       [ 1.06285383e+00, -5.90496966e-01],
       [-9.70451540e-01, -6.61042010e-01],
       [-8.38236609e-01,  2.19762109e+00],
       [ 3.51196953e-01,  6.74229484e-01],
       [-3.20728673e-01,  6.54209945e-01],
       [ 1.66583405e+00,  1.60053039e+00],
       [-1.

In [9]:
X_test

array([[-1.08246697, -0.44559363],
       [ 1.34080568, -0.81643177],
       [-0.13158787,  0.96181175],
       [-0.28784188, -0.81039413],
       [ 1.54530478, -0.56285094],
       [ 1.69638371,  1.23922537],
       [-1.1106795 ,  0.2598568 ],
       [ 0.70176684, -0.82342272],
       [-1.09899383, -0.69250129],
       [ 0.8525119 , -0.55268228],
       [-0.7881552 , -0.75986862],
       [ 0.22148609, -0.62608726],
       [ 1.63545132,  0.93925005],
       [ 0.90409575, -0.55363559],
       [-0.55978395, -0.82278718],
       [-1.10817543, -0.82405826],
       [-1.01485706, -0.73063374],
       [ 0.32916113,  0.96308284],
       [-0.9904841 ,  0.90079983],
       [-0.63841177, -0.56984189],
       [ 1.72710031,  2.01045429],
       [ 0.67722695, -0.59812346],
       [-0.93372517, -0.73095151],
       [ 1.03597681, -0.55268228],
       [-0.79850535,  0.31832656],
       [ 0.17958464, -0.6934546 ],
       [ 1.60523554,  1.95071344],
       [ 1.78903432, -0.81674954],
       [ 0.15888433,

In [10]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24  0]
 [ 2 14]]


0.95